/** Maps supported CSS declaration names to React Native style property names. */
export const propertyNames: Readonly<Record<string, string>> = {
  'align-content': 'alignContent',
  'align-items': 'alignItems',
  'align-self': 'alignSelf',
  'aspect-ratio': 'aspectRatio',
  'background-color': 'backgroundColor',
  'border-bottom-color': 'borderBottomColor',
  'border-bottom-left-radius': 'borderBottomLeftRadius',
  'border-bottom-right-radius': 'borderBottomRightRadius',
  'border-bottom-width': 'borderBottomWidth',
  'border-color': 'borderColor',
  'border-left-color': 'borderLeftColor',
  'border-left-width': 'borderLeftWidth',
  'border-radius': 'borderRadius',
  'border-right-color': 'borderRightColor',
  'border-right-width': 'borderRightWidth',
  'border-style': 'borderStyle',
  'border-top-color': 'borderTopColor',
  'border-top-left-radius': 'borderTopLeftRadius',
  'border-top-right-radius': 'borderTopRightRadius',
  'border-top-width': 'borderTopWidth',
  'border-width': 'borderWidth',
  bottom: 'bottom',
  color: 'color',
  display: 'display',
  flex: 'flex',
  'flex-basis': 'flexBasis',
  'flex-direction': 'flexDirection',
  'flex-grow': 'flexGrow',
  'flex-shrink': 'flexShrink',
  'flex-wrap': 'flexWrap',
  'font-size': 'fontSize',
  'font-style': 'fontStyle',
  'font-weight': 'fontWeight',
  gap: 'gap',
  height: 'height',
  'justify-content': 'justifyContent',
  left: 'left',
  'letter-spacing': 'letterSpacing',
  'line-height': 'lineHeight',
  margin: 'margin',
  'margin-bottom': 'marginBottom',
  'margin-left': 'marginLeft',
  'margin-right': 'marginRight',
  'margin-top': 'marginTop',
  'max-height': 'maxHeight',
  'max-width': 'maxWidth',
  'min-height': 'minHeight',
  'min-width': 'minWidth',
  opacity: 'opacity',
  overflow: 'overflow',
  padding: 'padding',
  'padding-bottom': 'paddingBottom',
  'padding-left': 'paddingLeft',
  'padding-right': 'paddingRight',
  'padding-top': 'paddingTop',
  position: 'position',
  right: 'right',
  'text-align': 'textAlign',
  'text-decoration-line': 'textDecorationLine',
  'text-transform': 'textTransform',
  top: 'top',
  width: 'width',
  'z-index': 'zIndex',
};

/** Expands CSS logical properties into React Native's physical properties. */
export const logicalProperties: Readonly<Record<string, readonly string[]>> = {
  'inset-inline': ['left', 'right'],
  'margin-block': ['marginTop', 'marginBottom'],
  'margin-inline': ['marginLeft', 'marginRight'],
  'padding-block': ['paddingTop', 'paddingBottom'],
  'padding-inline': ['paddingLeft', 'paddingRight'],
};
