import type { GroupDefinition } from './semantics-exact-groups';

/** Exact scrolling, scrollbar, snap, and form-control semantic groups. */
export const EXACT_INTERACTION_GROUPS: Readonly<Record<string, GroupDefinition>> = {
  'scroll-auto': { group: 'scroll-behavior' },
  'scroll-smooth': { group: 'scroll-behavior' },
  'scrollbar-auto': { group: 'scrollbar-width' },
  'scrollbar-thin': { group: 'scrollbar-width' },
  'scrollbar-none': { group: 'scrollbar-width' },
  'scrollbar-gutter-auto': { group: 'scrollbar-gutter' },
  'scrollbar-gutter-stable': { group: 'scrollbar-gutter' },
  'scrollbar-gutter-both': { group: 'scrollbar-gutter' },
  'border-collapse': { group: 'border-collapse' },
  'border-separate': { group: 'border-collapse' },
  'table-auto': { group: 'table-layout' },
  'table-fixed': { group: 'table-layout' },
  'caption-top': { group: 'caption-side' },
  'caption-bottom': { group: 'caption-side' },
  'snap-none': { group: 'scroll-snap-type' },
  'snap-x': { group: 'scroll-snap-type' },
  'snap-y': { group: 'scroll-snap-type' },
  'snap-both': { group: 'scroll-snap-type' },
  'snap-mandatory': { group: 'scroll-snap-strictness' },
  'snap-proximity': { group: 'scroll-snap-strictness' },
  'snap-normal': { group: 'scroll-snap-stop' },
  'snap-always': { group: 'scroll-snap-stop' },
  'snap-start': { group: 'scroll-snap-align' },
  'snap-end': { group: 'scroll-snap-align' },
  'snap-center': { group: 'scroll-snap-align' },
  'snap-align-none': { group: 'scroll-snap-align' },
  'forced-color-adjust-auto': { group: 'forced-color-adjust' },
  'forced-color-adjust-none': { group: 'forced-color-adjust' },
  'accent-auto': { group: 'accent-color' },
  'caret-auto': { group: 'caret-color' },
  'pointer-events-none': { group: 'pointer-events' },
  'pointer-events-auto': { group: 'pointer-events' },
  'select-none': { group: 'user-select' },
  'select-text': { group: 'user-select' },
  'select-all': { group: 'user-select' },
  'select-auto': { group: 'user-select' },
  'appearance-none': { group: 'appearance' },
  'appearance-auto': { group: 'appearance' },
  'field-sizing-content': { group: 'field-sizing' },
  'resize-none': { group: 'resize' },
  'resize-x': { group: 'resize' },
  'resize-y': { group: 'resize' },
  resize: { group: 'resize' },
};
