import type { GroupDefinition } from './semantics-exact-groups';

/** Exact layout, display, and flex utility semantic groups. */
export const EXACT_LAYOUT_GROUPS: Readonly<Record<string, GroupDefinition>> = {
  block: { group: 'display' },
  'inline-block': { group: 'display' },
  inline: { group: 'display' },
  flex: { group: 'display' },
  'inline-flex': { group: 'display' },
  grid: { group: 'display' },
  'inline-grid': { group: 'display' },
  table: { group: 'display' },
  'inline-table': { group: 'display' },
  'flow-root': { group: 'display' },
  contents: { group: 'display' },
  'list-item': { group: 'display' },
  'sr-only': { group: 'sr-only' },
  'not-sr-only': { group: 'sr-only' },
  hidden: { group: 'display' },
  static: { group: 'position' },
  fixed: { group: 'position' },
  absolute: { group: 'position' },
  relative: { group: 'position' },
  sticky: { group: 'position' },
  visible: { group: 'visibility' },
  invisible: { group: 'visibility' },
  collapse: { group: 'visibility' },
  'box-border': { group: 'box-sizing' },
  'box-content': { group: 'box-sizing' },
  isolate: { group: 'isolation' },
  'isolation-auto': { group: 'isolation' },
  'overflow-auto': { group: 'overflow' },
  'overflow-hidden': { group: 'overflow' },
  'overflow-clip': { group: 'overflow' },
  'overflow-visible': { group: 'overflow' },
  'overflow-scroll': { group: 'overflow' },
  container: { group: 'container' },
  'flex-row': { group: 'flex-direction' },
  'flex-row-reverse': { group: 'flex-direction' },
  'flex-col': { group: 'flex-direction' },
  'flex-col-reverse': { group: 'flex-direction' },
  'flex-wrap': { group: 'flex-wrap' },
  'flex-wrap-reverse': { group: 'flex-wrap' },
  'flex-nowrap': { group: 'flex-wrap' },
};
