import type { GroupDefinition } from './semantics-exact-groups';

/** Exact font, numeric, and text-transformation semantic groups. */
export const EXACT_TYPOGRAPHY_GROUPS: Readonly<Record<string, GroupDefinition>> = {
  'font-thin': { group: 'font-weight' },
  'font-extralight': { group: 'font-weight' },
  'font-light': { group: 'font-weight' },
  'font-normal': { group: 'font-weight' },
  'font-medium': { group: 'font-weight' },
  'font-semibold': { group: 'font-weight' },
  'font-bold': { group: 'font-weight' },
  'font-extrabold': { group: 'font-weight' },
  'font-black': { group: 'font-weight' },
  antialiased: { group: 'font-smoothing' },
  'subpixel-antialiased': { group: 'font-smoothing' },
  'normal-nums': { group: 'numeric-normal' },
  ordinal: { group: 'numeric-ordinal' },
  'slashed-zero': { group: 'numeric-slashed-zero' },
  'lining-nums': { group: 'numeric-lining-nums' },
  'oldstyle-nums': { group: 'numeric-oldstyle-nums' },
  'proportional-nums': { group: 'numeric-proportional-nums' },
  'tabular-nums': { group: 'numeric-tabular-nums' },
  'diagonal-fractions': { group: 'numeric-diagonal-fractions' },
  'stacked-fractions': { group: 'numeric-stacked-fractions' },
  italic: { group: 'font-style' },
  'not-italic': { group: 'font-style' },
  truncate: { group: 'truncate' },
  uppercase: { group: 'text-transform' },
  lowercase: { group: 'text-transform' },
  capitalize: { group: 'text-transform' },
  'normal-case': { group: 'text-transform' },
  underline: { group: 'text-decoration-line' },
  overline: { group: 'text-decoration-line' },
  'line-through': { group: 'text-decoration-line' },
  'no-underline': { group: 'text-decoration-line' },
};
