/** Supported pseudo-class variants and their selector fragments. */
export const PSEUDO_CLASS_VARIANTS: Readonly<Record<string, string>> = {
  hover: 'hover',
  focus: 'focus',
  'focus-visible': 'focus-visible',
  'focus-within': 'focus-within',
  active: 'active',
  disabled: 'disabled',
  visited: 'visited',
  checked: 'checked',
  indeterminate: 'indeterminate',
  default: 'default',
  valid: 'valid',
  invalid: 'invalid',
  'in-range': 'in-range',
  'out-of-range': 'out-of-range',
  'placeholder-shown': 'placeholder-shown',
  autofill: 'autofill',
  'read-only': 'read-only',
  required: 'required',
  optional: 'optional',
  open: 'open',
  target: 'target',
  empty: 'empty',
  enabled: 'enabled',
  first: 'first-child',
  last: 'last-child',
  only: 'only-child',
  odd: 'nth-child(odd)',
  even: 'nth-child(even)',
  'first-of-type': 'first-of-type',
  'last-of-type': 'last-of-type',
  'only-of-type': 'only-of-type',
};

/** Supported pseudo-element variants and their selector fragments. */
export const PSEUDO_ELEMENT_VARIANTS: Readonly<Record<string, string>> = {
  before: 'before',
  after: 'after',
  selection: 'selection',
  marker: 'marker',
  file: 'file-selector-button',
  'first-letter': 'first-letter',
  'first-line': 'first-line',
  placeholder: 'placeholder',
};
