/** Semantic group data for an exactly matched utility. */
export interface GroupDefinition {
  /** Primary semantic write group. */
  readonly group: string;
  /** Optional groups that this utility clears. */
  readonly conflicts?: readonly string[];
}

/** Exact utility-to-group table used before prefix classification. */
export const EXACT_GROUPS: Readonly<Record<string, GroupDefinition>> = {
  block: { group: 'display' },
  'inline-block': { group: 'display' },
  inline: { group: 'display' },
  flex: { group: 'display' },
  'inline-flex': { group: 'display' },
  grid: { group: 'display' },
  'inline-grid': { group: 'display' },
  table: { group: 'display' },
  'inline-table': { group: 'display' },
  'flow-root': { group: 'display' },
  contents: { group: 'display' },
  'list-item': { group: 'display' },
  'sr-only': { group: 'sr-only' },
  'not-sr-only': { group: 'sr-only' },
  hidden: { group: 'display' },
  static: { group: 'position' },
  fixed: { group: 'position' },
  absolute: { group: 'position' },
  relative: { group: 'position' },
  sticky: { group: 'position' },
  visible: { group: 'visibility' },
  invisible: { group: 'visibility' },
  collapse: { group: 'visibility' },
  'box-border': { group: 'box-sizing' },
  'box-content': { group: 'box-sizing' },
  isolate: { group: 'isolation' },
  'isolation-auto': { group: 'isolation' },
  border: { group: 'border-width' },
  'divide-x': { group: 'divide-x' },
  'divide-y': { group: 'divide-y' },
  outline: { group: 'outline-width' },
  'outline-none': { group: 'outline-style' },
  'outline-hidden': { group: 'outline-hidden' },
  'outline-solid': { group: 'outline-style' },
  'outline-dashed': { group: 'outline-style' },
  'outline-dotted': { group: 'outline-style' },
  'outline-double': { group: 'outline-style' },
  rounded: { group: 'border-radius' },
  shadow: { group: 'box-shadow' },
  transition: { group: 'transition-property' },
  transform: { group: 'transform' },
  'transform-none': { group: 'transform' },
  'transition-none': { group: 'transition-property' },
  'transition-normal': { group: 'transition-behavior' },
  'transition-discrete': { group: 'transition-behavior' },
  blur: { group: 'blur' },
  grayscale: { group: 'grayscale' },
  invert: { group: 'invert' },
  sepia: { group: 'sepia' },
  'drop-shadow': { group: 'drop-shadow' },
  'overflow-auto': { group: 'overflow' },
  'overflow-hidden': { group: 'overflow' },
  'overflow-clip': { group: 'overflow' },
  'overflow-visible': { group: 'overflow' },
  'overflow-scroll': { group: 'overflow' },
  container: { group: 'container' },
  'flex-row': { group: 'flex-direction' },
  'flex-row-reverse': { group: 'flex-direction' },
  'flex-col': { group: 'flex-direction' },
  'flex-col-reverse': { group: 'flex-direction' },
  'flex-wrap': { group: 'flex-wrap' },
  'flex-wrap-reverse': { group: 'flex-wrap' },
  'flex-nowrap': { group: 'flex-wrap' },
  'font-thin': { group: 'font-weight' },
  'font-extralight': { group: 'font-weight' },
  'font-light': { group: 'font-weight' },
  'font-normal': { group: 'font-weight' },
  'font-medium': { group: 'font-weight' },
  'font-semibold': { group: 'font-weight' },
  'font-bold': { group: 'font-weight' },
  'font-extrabold': { group: 'font-weight' },
  'font-black': { group: 'font-weight' },
  antialiased: { group: 'font-smoothing' },
  'subpixel-antialiased': { group: 'font-smoothing' },
  'normal-nums': { group: 'numeric-normal' },
  ordinal: { group: 'numeric-ordinal' },
  'slashed-zero': { group: 'numeric-slashed-zero' },
  'lining-nums': { group: 'numeric-lining-nums' },
  'oldstyle-nums': { group: 'numeric-oldstyle-nums' },
  'proportional-nums': { group: 'numeric-proportional-nums' },
