/**
 * CSS properties reset by supported shorthand declarations.
 *
 * These sets supplement explicit semantic data when declarations are atomized.
 * They keep later shorthand utilities from leaving earlier longhand utilities in
 * effect, matching CSS shorthand reset behavior during compiled-style merging.
 */
export const SHORTHAND_WRITE_SETS: Readonly<Record<string, readonly string[]>> = {
  font: [
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'font-stretch',
    'line-height',
    'font-kerning',
    'font-feature-settings',
    'font-variation-settings',
  ],
  background: [
    'background-attachment',
    'background-color',
    'background-image',
    'background-position',
    'background-repeat',
    'background-size',
    'background-origin',
    'background-clip',
  ],
  border: [
    'border-width',
    'border-style',
    'border-color',
    'border-top',
    'border-right',
    'border-bottom',
    'border-left',
    'border-top-width',
    'border-right-width',
    'border-bottom-width',
    'border-left-width',
  ],
  animation: [
    'animation-name',
    'animation-duration',
    'animation-timing-function',
    'animation-delay',
    'animation-iteration-count',
    'animation-direction',
    'animation-fill-mode',
    'animation-play-state',
    'animation-composition',
    'animation-timeline',
    'animation-range',
    'animation-range-start',
    'animation-range-end',
  ],
  'animation-range': ['animation-range-start', 'animation-range-end'],
  grid: [
    'grid-template-columns',
    'grid-template-rows',
    'grid-template-areas',
    'grid-auto-columns',
    'grid-auto-rows',
    'grid-auto-flow',
    'grid-column',
    'grid-row',
  ],
  mask: [
    'mask-image',
    'mask-mode',
    'mask-position',
    'mask-size',
    'mask-repeat',
    'mask-origin',
    'mask-clip',
    'mask-composite',
  ],
  transition: [
    'transition-property',
    'transition-duration',
    'transition-timing-function',
    'transition-delay',
    'transition-behavior',
  ],
  container: ['container-name', 'container-type'],
};
