import type { UtilityDeclaration } from './utility-types';

/** Exact alignment utility declarations keyed by their complete candidate. */
export const EXACT_ALIGNMENT_DECLARATIONS: Readonly<Record<string, readonly UtilityDeclaration[]>> = {
  'items-start': [{ property: 'align-items', value: 'flex-start' }],
  'items-center': [{ property: 'align-items', value: 'center' }],
  'items-end': [{ property: 'align-items', value: 'flex-end' }],
  'items-stretch': [{ property: 'align-items', value: 'stretch' }],
  'items-baseline': [{ property: 'align-items', value: 'baseline' }],
  'justify-start': [{ property: 'justify-content', value: 'flex-start' }],
  'justify-center': [{ property: 'justify-content', value: 'center' }],
  'justify-end': [{ property: 'justify-content', value: 'flex-end' }],
  'justify-between': [{ property: 'justify-content', value: 'space-between' }],
  'justify-around': [{ property: 'justify-content', value: 'space-around' }],
  'justify-evenly': [{ property: 'justify-content', value: 'space-evenly' }],
  'self-auto': [{ property: 'align-self', value: 'auto' }],
  'self-start': [{ property: 'align-self', value: 'flex-start' }],
  'self-center': [{ property: 'align-self', value: 'center' }],
  'self-end': [{ property: 'align-self', value: 'flex-end' }],
  'self-stretch': [{ property: 'align-self', value: 'stretch' }],
  'self-baseline': [{ property: 'align-self', value: 'baseline' }],
  'justify-items-start': [{ property: 'justify-items', value: 'start' }],
  'justify-items-center': [{ property: 'justify-items', value: 'center' }],
  'justify-items-end': [{ property: 'justify-items', value: 'end' }],
  'justify-items-stretch': [{ property: 'justify-items', value: 'stretch' }],
  'justify-self-auto': [{ property: 'justify-self', value: 'auto' }],
  'justify-self-start': [{ property: 'justify-self', value: 'start' }],
  'justify-self-center': [{ property: 'justify-self', value: 'center' }],
  'justify-self-end': [{ property: 'justify-self', value: 'end' }],
  'justify-self-stretch': [{ property: 'justify-self', value: 'stretch' }],
  'place-items-start': [{ property: 'place-items', value: 'start' }],
  'place-items-center': [{ property: 'place-items', value: 'center' }],
  'place-items-end': [{ property: 'place-items', value: 'end' }],
  'place-items-stretch': [{ property: 'place-items', value: 'stretch' }],
  'place-items-baseline': [{ property: 'place-items', value: 'baseline' }],
  'place-self-auto': [{ property: 'place-self', value: 'auto' }],
  'place-self-start': [{ property: 'place-self', value: 'start' }],
  'place-self-center': [{ property: 'place-self', value: 'center' }],
  'place-self-end': [{ property: 'place-self', value: 'end' }],
  'place-self-stretch': [{ property: 'place-self', value: 'stretch' }],
  'place-content-start': [{ property: 'place-content', value: 'start' }],
  'place-content-center': [{ property: 'place-content', value: 'center' }],
  'place-content-end': [{ property: 'place-content', value: 'end' }],
  'place-content-between': [{ property: 'place-content', value: 'space-between' }],
  'place-content-around': [{ property: 'place-content', value: 'space-around' }],
  'place-content-evenly': [{ property: 'place-content', value: 'space-evenly' }],
  'place-content-stretch': [{ property: 'place-content', value: 'stretch' }],
};
