'use strict';

/** Lists fixed utility strings that have no value segment. */
const EXACT = [
  'block',
  'inline',
  'inline-block',
  'flow-root',
  'contents',
  'flex',
  'inline-flex',
  'grid',
  'inline-grid',
  'hidden',
  'static',
  'fixed',
  'absolute',
  'relative',
  'sticky',
  'visible',
  'invisible',
  'sr-only',
  'not-sr-only',
  'flex-row',
  'flex-row-reverse',
  'flex-col',
  'flex-col-reverse',
  'flex-wrap',
  'flex-wrap-reverse',
  'flex-nowrap',
  'items-start',
  'items-center',
  'items-end',
  'items-stretch',
  'items-baseline',
  'justify-start',
  'justify-center',
  'justify-end',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'font-sans',
  'font-serif',
  'font-mono',
  'font-normal',
  'font-medium',
  'font-semibold',
  'font-bold',
  'italic',
  'not-italic',
  'antialiased',
  'subpixel-antialiased',
  'normal-nums',
  'tabular-nums',
  'slashed-zero',
  'uppercase',
  'lowercase',
  'capitalize',
  'normal-case',
  'underline',
  'no-underline',
  'bg-none',
  'bg-auto',
  'bg-cover',
  'bg-contain',
  'shadow',
  'shadow-none',
  'ring',
  'ring-0',
  'filter-none',
  'backdrop-filter-none',
  'transition',
  'transition-none',
  'transition-all',
  'transition-colors',
  'transition-opacity',
  'transition-shadow',
  'transition-transform',
  'transition-transform-opacity',
  'transition-filter',
  'transition-size',
  'transition-normal',
  'transition-discrete',
  'transform',
  'transform-none',
  'animate-spin',
  'animate-ping',
  'animate-pulse',
  'animate-bounce',
  'animate-fade-in',
  'animate-fade-out',
  'animate-slide-in-up',
  'animate-slide-in-down',
  'animate-slide-in-left',
  'animate-slide-in-right',
  'animate-scale-in',
  'animate-scale-out',
  'animate-shimmer',
  'animation-name-none',
  'animation-duration-auto',
  'animation-running',
  'animation-paused',
  'animation-composition-replace',
  'animation-composition-add',
  'animation-composition-accumulate',
  'stagger-reverse',
  'delay-stagger',
  'animation-delay-stagger',
  'animation-timeline-auto',
  'animation-timeline-none',
  'animation-timeline-scroll-block',
  'animation-timeline-scroll-inline',
  'animation-timeline-view-block',
  'animation-timeline-view-inline',
  'timeline-scope-all',
  'view-transition-name-none',
  'view-transition-name-match',
  'view-transition-class-none',
  'content-visibility-visible',
  'content-visibility-auto',
  'content-visibility-hidden',
  'contain-none',
  'contain-content',
  'contain-strict',
  'contain-size',
  'contain-inline-size',
  'contain-layout',
  'contain-style',
  'contain-paint',
  'stroke-cap-butt',
  'stroke-cap-round',
  'stroke-cap-square',
  'stroke-join-miter',
  'stroke-join-round',
  'stroke-join-bevel',
  'fill-rule-nonzero',
  'fill-rule-evenodd',
  'clip-rule-nonzero',
  'clip-rule-evenodd',
  'vector-effect-none',
  'vector-effect-non-scaling-stroke',
  'paint-order-normal',
  'paint-order-fill',
  'paint-order-stroke',
  'paint-order-markers',
  'shape-rendering-auto',
  'shape-rendering-optimize-speed',
  'shape-rendering-crisp-edges',
  'shape-rendering-geometric-precision',
  'writing-horizontal-tb',
  'writing-vertical-rl',
  'writing-vertical-lr',
  'text-orientation-mixed',
  'text-orientation-upright',
  'text-orientation-sideways',
  'text-combine-upright-none',
  'text-combine-upright-all',
  'unicode-bidi-normal',
  'unicode-bidi-embed',
  'unicode-bidi-isolate',
  'unicode-bidi-bidi-override',
  'unicode-bidi-isolate-override',
  'unicode-bidi-plaintext',
  'image-render-auto',
  'image-render-crisp-edges',
  'image-render-pixelated',
  'font-optical-auto',
  'font-optical-none',
  'font-kerning-auto',
  'font-kerning-normal',
  'font-kerning-none',
  'font-synthesis-none',
  'font-synthesis-weight',
  'font-synthesis-style',
  'font-synthesis-small-caps',
  'font-synthesis-position',
  'pointer-events-none',
  'pointer-events-auto',
  'select-none',
  'select-text',
  'select-all',
  'select-auto',
  'container',
];

/** Maps utility prefixes with values to their completion descriptions. */
const RECIPES = [
  ['p-', 'Spacing'],
  ['m-', 'Spacing'],
  ['gap-', 'Gap'],
  ['w-', 'Width'],
  ['h-', 'Height'],
  ['size-', 'Size'],
  ['min-w-', 'Minimum width'],
  ['max-w-', 'Maximum width'],
  ['min-h-', 'Minimum height'],
  ['max-h-', 'Maximum height'],
  ['text-', 'Typography or color'],
  ['bg-', 'Background'],
  ['border-', 'Border'],
  ['rounded-', 'Border radius'],
  ['outline-', 'Outline'],
  ['ring-', 'Ring'],
  ['shadow-', 'Shadow'],
  ['opacity-', 'Opacity'],
  ['transition-', 'Transition property'],
  ['duration-', 'Transition duration'],
  ['delay-', 'Transition delay'],
  ['ease-', 'Transition timing'],
  ['animation-name-', 'Animation name'],
  ['animation-duration-', 'Animation duration'],
  ['animation-delay-', 'Animation delay'],
  ['animation-ease-', 'Animation timing function'],
  ['animation-iterations-', 'Animation iteration count'],
  ['animation-direction-', 'Animation direction'],
  ['animation-fill-', 'Animation fill mode'],
  ['animation-composition-', 'Animation composition'],
  ['stagger-', 'Stagger timing'],
  ['stagger-index-', 'Stagger index'],
  ['stagger-count-', 'Stagger count'],
  ['animation-timeline-', 'Animation timeline'],
  ['scroll-timeline-', 'Scroll timeline'],
  ['view-timeline-', 'View timeline'],
  ['timeline-scope-', 'Timeline scope'],
  ['animation-range-', 'Animation attachment range'],
  ['view-transition-name-', 'View Transition name'],
  ['view-transition-class-', 'View Transition class'],
  ['contain-intrinsic-size-', 'Contain intrinsic size'],
  ['contain-intrinsic-inline-size-', 'Contain intrinsic inline size'],
  ['contain-intrinsic-block-size-', 'Contain intrinsic block size'],
  ['stroke-miterlimit-', 'SVG stroke miter limit'],
  ['stroke-dasharray-', 'SVG stroke dash pattern'],
  ['stroke-dashoffset-', 'SVG stroke dash offset'],
  ['translate-x-', 'Translation'],
  ['translate-y-', 'Translation'],
  ['scale-', 'Scale'],
  ['scale-x-', 'X scale'],
  ['scale-y-', 'Y scale'],
  ['rotate-', 'Rotation'],
  ['skew-x-', 'X skew'],
  ['skew-y-', 'Y skew'],
  ['grid-cols-', 'Grid columns'],
  ['grid-rows-', 'Grid rows'],
  ['col-span-', 'Grid column span'],
  ['row-span-', 'Grid row span'],
  ['from-', 'Gradient start'],
  ['via-', 'Gradient middle'],
  ['to-', 'Gradient end'],
  ['blur-', 'Filter blur'],
  ['backdrop-blur-', 'Backdrop blur'],
];

/** Lists prefixes that change how a utility is applied. */
const VARIANTS = [
  'sm:',
  'md:',
  'lg:',
  'xl:',
  '2xl:',
  'hover:',
  'focus:',
  'focus-visible:',
  'focus-within:',
  'active:',
  'disabled:',
  'enabled:',
  'checked:',
  'required:',
  'invalid:',
  'valid:',
  'first:',
  'last:',
  'odd:',
  'even:',
  'before:',
  'after:',
  'selection:',
  'dark:',
  'motion-safe:',
  'motion-reduce:',
  'starting:',
  'print:',
  'group-hover:',
  'group-focus:',
  'state-[name]:',
  'group-state-[name]:',
  'peer-state-[name]:',
  'peer-checked:',
  'has-checked:',
  'in-focus:',
  'not-hover:',
  'data-active:',
  'aria-expanded:',
  'supports-[display:grid]:',
  'not-supports-[display:grid]:',
  'max-md:',
  'min-[900px]:',
  'vt-old-[target]:',
  'vt-new-[target]:',
  'vt-group-[target]:',
  'vt-image-pair-[target]:',
  '*:',
  '**:',
];

/**
 * Gets completion entries that start with a prefix.
 *
 * @param {string} prefix - Text already typed by the user.
 * @returns {{label: string, detail: string}[]} Matching completion entries.
 */
function entries(prefix) {
  const items = EXACT.map((label) => ({ label, detail: 'CSSX utility' }))
    .concat(RECIPES.map(([label, detail]) => ({ label, detail: `${detail} utility family` })))
    .concat(VARIANTS.map((label) => ({ label, detail: 'CSSX variant' })));
  return items.filter((item) => item.label.startsWith(prefix));
}

/**
 * Gets short help text for one utility.
 *
 * @param {string} candidate - A CSSX utility string.
 * @returns {string | null} Help text, or null when the utility is unknown.
 */
function documentation(candidate) {
  const base = candidate.split(':').at(-1).replace(/^!|-$/g, '');
  const exact = EXACT.includes(base);
  const recipe = RECIPES.find(([prefix]) => base.startsWith(prefix));
  return exact
    ? `**${base}** — CSSX utility.`
    : recipe
      ? `**${base}** — ${recipe[1]} utility. Values are resolved during compilation.`
      : null;
}

module.exports = { entries, documentation };
