'use strict';

/** Lists fixed utility strings that have no value segment. */
const EXACT = [
  'block',
  'inline',
  'inline-block',
  'flow-root',
  'contents',
  'flex',
  'inline-flex',
  'grid',
  'inline-grid',
  'hidden',
  'static',
  'fixed',
  'absolute',
  'relative',
  'sticky',
  'visible',
  'invisible',
  'sr-only',
  'not-sr-only',
  'flex-row',
  'flex-row-reverse',
  'flex-col',
  'flex-col-reverse',
  'flex-wrap',
  'flex-wrap-reverse',
  'flex-nowrap',
  'items-start',
  'items-center',
  'items-end',
  'items-stretch',
  'items-baseline',
  'justify-start',
  'justify-center',
  'justify-end',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'font-sans',
  'font-serif',
  'font-mono',
  'font-normal',
  'font-medium',
  'font-semibold',
  'font-bold',
  'italic',
  'not-italic',
  'antialiased',
  'subpixel-antialiased',
  'normal-nums',
  'tabular-nums',
  'slashed-zero',
  'uppercase',
  'lowercase',
  'capitalize',
  'normal-case',
  'underline',
  'no-underline',
  'bg-none',
  'bg-auto',
  'bg-cover',
  'bg-contain',
  'shadow',
  'shadow-none',
  'ring',
  'ring-0',
  'filter-none',
  'backdrop-filter-none',
  'transition',
  'transition-none',
  'transform',
  'transform-none',
  'animate-spin',
  'animate-ping',
  'animate-pulse',
  'animate-bounce',
  'animation-running',
  'animation-paused',
  'content-visibility-visible',
  'content-visibility-auto',
  'content-visibility-hidden',
  'contain-none',
  'contain-content',
  'contain-strict',
  'contain-size',
  'contain-inline-size',
  'contain-layout',
  'contain-style',
  'contain-paint',
  'stroke-cap-butt',
  'stroke-cap-round',
  'stroke-cap-square',
  'stroke-join-miter',
  'stroke-join-round',
  'stroke-join-bevel',
  'fill-rule-nonzero',
  'fill-rule-evenodd',
  'clip-rule-nonzero',
  'clip-rule-evenodd',
  'vector-effect-none',
  'vector-effect-non-scaling-stroke',
  'paint-order-normal',
  'paint-order-fill',
  'paint-order-stroke',
  'paint-order-markers',
  'shape-rendering-auto',
  'shape-rendering-optimize-speed',
  'shape-rendering-crisp-edges',
  'shape-rendering-geometric-precision',
  'writing-horizontal-tb',
  'writing-vertical-rl',
  'writing-vertical-lr',
  'text-orientation-mixed',
  'text-orientation-upright',
  'text-orientation-sideways',
  'text-combine-upright-none',
  'text-combine-upright-all',
  'unicode-bidi-normal',
  'unicode-bidi-embed',
  'unicode-bidi-isolate',
  'unicode-bidi-bidi-override',
  'unicode-bidi-isolate-override',
  'unicode-bidi-plaintext',
  'image-render-auto',
  'image-render-crisp-edges',
  'image-render-pixelated',
  'font-optical-auto',
  'font-optical-none',
  'font-kerning-auto',
  'font-kerning-normal',
  'font-kerning-none',
  'font-synthesis-none',
  'font-synthesis-weight',
  'font-synthesis-style',
  'font-synthesis-small-caps',
  'font-synthesis-position',
  'pointer-events-none',
  'pointer-events-auto',
  'select-none',
  'select-text',
  'select-all',
  'select-auto',
  'container',
];

/** Maps utility prefixes with values to their completion descriptions. */
const RECIPES = [
  ['p-', 'Spacing'],
  ['m-', 'Spacing'],
  ['gap-', 'Gap'],
  ['w-', 'Width'],
  ['h-', 'Height'],
  ['size-', 'Size'],
  ['min-w-', 'Minimum width'],
  ['max-w-', 'Maximum width'],
  ['min-h-', 'Minimum height'],
  ['max-h-', 'Maximum height'],
  ['text-', 'Typography or color'],
  ['bg-', 'Background'],
  ['border-', 'Border'],
  ['rounded-', 'Border radius'],
  ['outline-', 'Outline'],
  ['ring-', 'Ring'],
  ['shadow-', 'Shadow'],
