import { describe, expect, it } from 'vitest';
import { compileStyleRecords, compileUtilities } from '../src/index';

const CANDIDATES = [
  'block',
  'table-cell',
  'sr-only',
  'relative',
  'overflow-x-scroll',
  'overscroll-y-contain',
  'isolate',
  'container',
  'aspect-video',
  'columns-3',
  'break-before-column',
  'break-after-avoid-page',
  'break-inside-avoid-column',
  'box-decoration-clone',
  'box-border',
  'float-start',
  'clear-both',
  'object-cover',
  'w-1/2',
  'max-w-3xl',
  'size-4',
  'inline-full',
  'min-inline-0',
  'block-4',
  'top-2',
  'inset-s-4',
  'z-10',
  'flex-row',
  'flex-1',
  'grow',
  'basis-1/3',
  'order-last',
  'items-center',
  'place-content-between',
  'grid-cols-3',
  'grid-rows-subgrid',
  'col-span-2',
  'row-start-3',
  'grid-flow-col-dense',
  'auto-cols-fr',
  'p-4',
  '-mx-2',
  'gap-x-3',
  'space-y-reverse',
  'divide-x-2',
  'divide-blue-500',
  'border-separate',
  'border-spacing-x-2',
  'table-fixed',
  'caption-bottom',
  'scroll-pt-4',
  'tab-4',
  'line-clamp-2',
  'font-sans',
  'font-semibold',
  'text-sm',
  'text-blue-500/50',
  'leading-tight',
  'tracking-wide',
  'tabular-nums',
  'underline',
  'decoration-wavy',
  'decoration-blue-500',
  'underline-offset-4',
  "before:content-['required']",
  'content-none',
  'bg-cover',
  'bg-position-[25%_75%]',
  'bg-linear-to-r/oklch',
  'from-red-500',
  'via-blue-500/50',
  'to-90%',
  'border-x-2',
  'border-red-500',
  'outline-dashed',
  'ring-2',
  'ring-offset-blue-500',
  'shadow-md',
  'shadow-2xl',
  'blur-sm',
  'backdrop-blur-md',
  'mask-[url("/mask.svg")]',
  'mask-repeat-x',
  'transition-colors',
  'transition-discrete',
  'duration-200',
  'animation-duration-500',
  'animation-delay-[150ms]',
  'animation-ease-out',
  'animation-iterations-infinite',
  'animation-direction-alternate',
  'animation-fill-both',
  'animation-running',
  'animate-spin',
  'translate-x-2',
  'scale-y-95',
  'skew-x-6',
  'cursor-pointer',
  'resize-x',
  'touch-pan-x',
  'select-none',
  'snap-always',
  'scrollbar-gutter-stable',
  'scrollbar-thumb-red-500',
  'will-change-transform',
  'accent-blue-500',
  'caret-red-500',
  'scheme-dark',
  'fill-green-500',
  'stroke-[3px]',
  'stroke-cap-round',
  'stroke-dasharray-[4_8]',
  'vector-effect-non-scaling-stroke',
  'writing-vertical-rl',
  'image-render-pixelated',
  'font-optical-auto',
  'content-visibility-auto',
  'contain-[layout_paint]',
  'contain-intrinsic-size-[auto_800px]',
  'forced-color-adjust-none',
  '[mask-type:luminance]',
  'sm:hover:bg-red-500',
  'group-focus:text-white',
  'state-[open]:shadow-xl',
  'has-checked:ring-2',
  'not-supports-[display:grid]:flex',
  '*:p-2',
] as const;

const INVALID_CANDIDATES = [
  ['columns', 'columns-fluid'],
  ['breaks', 'break-inside-page'],
  ['object position', 'object-middle'],
  ['dimension', 'w-enormous'],
  ['flex', 'flex-stretch'],
  ['grid', 'grid-cols-many'],
  ['spacing', 'p-comfortable'],
  ['table', 'border-spacing-z-2'],
  ['typography', 'font-strongest'],
  ['content', 'content-label'],
  ['background', 'bg-spotlight'],
  ['gradient', 'from-101%'],
  ['border', 'border-z-2'],
  ['outline', 'outline-dottedly'],
  ['ring', 'ring-3'],
  ['filter', 'blur-ultra'],
  ['mask', 'mask-repeat-diagonal'],
  ['transition', 'duration-slow'],
  ['animation', 'animate-unknown'],
  ['animation longhand', 'animation-duration-slow'],
  ['containment', 'contain-layout-paint'],
  ['SVG rendering', 'stroke-cap-rounded'],
  ['writing mode', 'writing-vertical'],
  ['transform', 'translate-z-4'],
  ['interaction', 'touch-pan-z'],
  ['scrolling', 'snap-forever'],
  ['SVG', 'stroke-width-2'],
  ['arbitrary property', '[mask-type:luminance;display:block]'],
] as const;

describe('CSSX compiler/conformance matrix', () => {
  it('classifies and emits each supported utility family through the same owned recipes', async () => {
    const source = Object.fromEntries(CANDIDATES.map((candidate, index) => [`style${index}`, candidate]));
    const packed = compileStyleRecords(source);
    const compiled = await compileUtilities(CANDIDATES, (candidate) => packed.classes[candidate] ?? '');

    expect(Object.values(packed.styles).flatMap((style) => style._)).not.toHaveLength(0);
    expect(Object.keys(compiled.classes).sort()).toEqual([...CANDIDATES].sort());
    expect(compiled.css).toContain('padding:calc(0.25rem * 4)');
    expect(compiled.css).toContain('mask-image:url("/mask.svg")');
    expect(compiled.css).toContain('@media (width >= 40rem)');
  });

  it.each(INVALID_CANDIDATES)('rejects invalid %s candidates', (_family, candidate) => {
    expect(() => compileStyleRecords({ root: candidate })).toThrow();
  });
});
